### ISSUE TITLE
Implement JetStream

### ISSUE THREAD

**Issue by viztea** [dimensional-fun/nats.kt#4]
Here's a partial TODO list for my JetStream implementation.

<sub>
I really, I mean really hate NATS and their lack of documentation on how to implement JetStream, I'm not quite sure how their own clients get worked on... unless they had internal docs but why wouldn't they release them!?!?!??! A lot of the current code is inspired by the java client but it's the messiest and most perplexing library I've ever laid my eyes on... So far, I've been able to implement all the things I would need for my own projects. Performance is still slightly worse than Java but it's like 2ms vs 200μs for a simple KV get
</sub> 

## TODO

- [ ] Streams
	- [x] Info
	- [x] List Info / Names
	- [x] Create
	- [ ] Delete
	- [ ] Purge
	- [ ] Seal
	- [ ] Update
- [ ] Messages
	- [x] Get
	- [ ] Delete 
- [ ] Consumers
	- [x] Create
	- [x] List Info / Names
- [ ] Object Storage
	- [ ] Buckets
		- [ ] Info
		- [ ] List Info / Names
		- [ ] Create
		- [ ] Delete
	- [ ] Objects
- [ ] Key Value
	- [x] Buckets
		- [x] Info
		- [x] List Info / Names
		- [x] Create
		- [x] Delete
	- [ ] Entries
		- [x] Get (Revision)
		- [x] Set
		- [x] Update
		- [x] Purge
		- [x] Delete
		- [ ] Watch
- [ ] Advisory

---

I need to dive into the consumer api of the official clients because there's no documentation and the json schemas I'm using don't give me enough info
